Updates.
Signed-off-by: James Puellmann <james.puellmann@gmail.com>

diff --git a/nocapslock b/nocapslock
--- a/nocapslock
+++ b/nocapslock
@@ -15,11 +15,11 @@ if type setxkbmap >/dev/null 2>&1; then
 fi
 
 # You have to be root to remap the console keyboard.
-if [ "$(id -u)" != "0" ]; then
-    echo "This script is not running as root so the console CapsLock cannot be remapped."
-    echo "Perhaps you forgot to run this under sudo. Note that this problem does not effect X."
-    echo "This only effects the consoles running on Alt-f1 through Alt-f6."
-    exit 2
-fi
+# if [ "$(id -u)" != "0" ]; then
+    # echo "This script is not running as root so the console CapsLock cannot be remapped."
+    # echo "Perhaps you forgot to run this under sudo. Note that this problem does not effect X."
+    # echo "This only effects the consoles running on Alt-f1 through Alt-f6."
+    # exit 2
+# fi
 # Remap the CapsLock key to a Control key for the console.
-(dumpkeys | grep keymaps; echo "keycode 58 = Control") | loadkeys
+(sudo dumpkeys | grep keymaps; echo "keycode 58 = Control") | sudo loadkeys
